// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"notification-service/ent/entitytype"
	"notification-service/ent/friendship"
	"notification-service/ent/friendshipstatus"
	"notification-service/ent/notification"
	"notification-service/ent/notificationchange"
	"notification-service/ent/notificationobjectid"
	"notification-service/ent/schema"
	"notification-service/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	entitytypeMixin := schema.EntityType{}.Mixin()
	entitytypeMixinHooks0 := entitytypeMixin[0].Hooks()
	entitytype.Hooks[0] = entitytypeMixinHooks0[0]
	entitytypeMixinInters0 := entitytypeMixin[0].Interceptors()
	entitytype.Interceptors[0] = entitytypeMixinInters0[0]
	friendshipMixin := schema.Friendship{}.Mixin()
	friendshipMixinHooks0 := friendshipMixin[0].Hooks()
	friendship.Hooks[0] = friendshipMixinHooks0[0]
	friendshipMixinInters0 := friendshipMixin[0].Interceptors()
	friendship.Interceptors[0] = friendshipMixinInters0[0]
	friendshipstatusMixin := schema.FriendshipStatus{}.Mixin()
	friendshipstatusMixinHooks0 := friendshipstatusMixin[0].Hooks()
	friendshipstatus.Hooks[0] = friendshipstatusMixinHooks0[0]
	friendshipstatusMixinInters0 := friendshipstatusMixin[0].Interceptors()
	friendshipstatus.Interceptors[0] = friendshipstatusMixinInters0[0]
	notificationMixin := schema.Notification{}.Mixin()
	notificationMixinHooks0 := notificationMixin[0].Hooks()
	notification.Hooks[0] = notificationMixinHooks0[0]
	notificationMixinInters0 := notificationMixin[0].Interceptors()
	notification.Interceptors[0] = notificationMixinInters0[0]
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescIsRead is the schema descriptor for isRead field.
	notificationDescIsRead := notificationFields[0].Descriptor()
	// notification.DefaultIsRead holds the default value on creation for the isRead field.
	notification.DefaultIsRead = notificationDescIsRead.Default.(bool)
	notificationchangeMixin := schema.NotificationChange{}.Mixin()
	notificationchangeMixinHooks0 := notificationchangeMixin[0].Hooks()
	notificationchange.Hooks[0] = notificationchangeMixinHooks0[0]
	notificationchangeMixinInters0 := notificationchangeMixin[0].Interceptors()
	notificationchange.Interceptors[0] = notificationchangeMixinInters0[0]
	notificationobjectidMixin := schema.NotificationObjectID{}.Mixin()
	notificationobjectidMixinHooks0 := notificationobjectidMixin[0].Hooks()
	notificationobjectid.Hooks[0] = notificationobjectidMixinHooks0[0]
	notificationobjectidMixinInters0 := notificationobjectidMixin[0].Interceptors()
	notificationobjectid.Interceptors[0] = notificationobjectidMixinInters0[0]
	notificationobjectidFields := schema.NotificationObjectID{}.Fields()
	_ = notificationobjectidFields
	// notificationobjectidDescEntityID is the schema descriptor for entity_id field.
	notificationobjectidDescEntityID := notificationobjectidFields[0].Descriptor()
	// notificationobjectid.EntityIDValidator is a validator for the "entity_id" field. It is called by the builders before save.
	notificationobjectid.EntityIDValidator = notificationobjectidDescEntityID.Validators[0].(func(int) error)
	userMixin := schema.User{}.Mixin()
	userMixinHooks0 := userMixin[0].Hooks()
	user.Hooks[0] = userMixinHooks0[0]
	userMixinInters0 := userMixin[0].Interceptors()
	user.Interceptors[0] = userMixinInters0[0]
}

const (
	Version = "v0.13.1"                                         // Version of ent codegen.
	Sum     = "h1:uD8QwN1h6SNphdCCzmkMN3feSUzNnVvV/WIkHKMbzOE=" // Sum of ent codegen.
)
