// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notification-service/ent/entitytype"
	"notification-service/ent/notificationobjectid"
	"notification-service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntityTypeUpdate is the builder for updating EntityType entities.
type EntityTypeUpdate struct {
	config
	hooks    []Hook
	mutation *EntityTypeMutation
}

// Where appends a list predicates to the EntityTypeUpdate builder.
func (etu *EntityTypeUpdate) Where(ps ...predicate.EntityType) *EntityTypeUpdate {
	etu.mutation.Where(ps...)
	return etu
}

// SetDeleteTime sets the "delete_time" field.
func (etu *EntityTypeUpdate) SetDeleteTime(t time.Time) *EntityTypeUpdate {
	etu.mutation.SetDeleteTime(t)
	return etu
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (etu *EntityTypeUpdate) SetNillableDeleteTime(t *time.Time) *EntityTypeUpdate {
	if t != nil {
		etu.SetDeleteTime(*t)
	}
	return etu
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (etu *EntityTypeUpdate) ClearDeleteTime() *EntityTypeUpdate {
	etu.mutation.ClearDeleteTime()
	return etu
}

// SetEntityName sets the "entityName" field.
func (etu *EntityTypeUpdate) SetEntityName(s string) *EntityTypeUpdate {
	etu.mutation.SetEntityName(s)
	return etu
}

// SetNillableEntityName sets the "entityName" field if the given value is not nil.
func (etu *EntityTypeUpdate) SetNillableEntityName(s *string) *EntityTypeUpdate {
	if s != nil {
		etu.SetEntityName(*s)
	}
	return etu
}

// SetNotificationDescription sets the "notificationDescription" field.
func (etu *EntityTypeUpdate) SetNotificationDescription(s string) *EntityTypeUpdate {
	etu.mutation.SetNotificationDescription(s)
	return etu
}

// SetNillableNotificationDescription sets the "notificationDescription" field if the given value is not nil.
func (etu *EntityTypeUpdate) SetNillableNotificationDescription(s *string) *EntityTypeUpdate {
	if s != nil {
		etu.SetNotificationDescription(*s)
	}
	return etu
}

// AddNotificationObjectIDIDs adds the "notificationObjectIDs" edge to the NotificationObjectID entity by IDs.
func (etu *EntityTypeUpdate) AddNotificationObjectIDIDs(ids ...int) *EntityTypeUpdate {
	etu.mutation.AddNotificationObjectIDIDs(ids...)
	return etu
}

// AddNotificationObjectIDs adds the "notificationObjectIDs" edges to the NotificationObjectID entity.
func (etu *EntityTypeUpdate) AddNotificationObjectIDs(n ...*NotificationObjectID) *EntityTypeUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return etu.AddNotificationObjectIDIDs(ids...)
}

// Mutation returns the EntityTypeMutation object of the builder.
func (etu *EntityTypeUpdate) Mutation() *EntityTypeMutation {
	return etu.mutation
}

// ClearNotificationObjectIDs clears all "notificationObjectIDs" edges to the NotificationObjectID entity.
func (etu *EntityTypeUpdate) ClearNotificationObjectIDs() *EntityTypeUpdate {
	etu.mutation.ClearNotificationObjectIDs()
	return etu
}

// RemoveNotificationObjectIDIDs removes the "notificationObjectIDs" edge to NotificationObjectID entities by IDs.
func (etu *EntityTypeUpdate) RemoveNotificationObjectIDIDs(ids ...int) *EntityTypeUpdate {
	etu.mutation.RemoveNotificationObjectIDIDs(ids...)
	return etu
}

// RemoveNotificationObjectIDs removes "notificationObjectIDs" edges to NotificationObjectID entities.
func (etu *EntityTypeUpdate) RemoveNotificationObjectIDs(n ...*NotificationObjectID) *EntityTypeUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return etu.RemoveNotificationObjectIDIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (etu *EntityTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, etu.sqlSave, etu.mutation, etu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (etu *EntityTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := etu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (etu *EntityTypeUpdate) Exec(ctx context.Context) error {
	_, err := etu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (etu *EntityTypeUpdate) ExecX(ctx context.Context) {
	if err := etu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (etu *EntityTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(entitytype.Table, entitytype.Columns, sqlgraph.NewFieldSpec(entitytype.FieldID, field.TypeInt))
	if ps := etu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := etu.mutation.DeleteTime(); ok {
		_spec.SetField(entitytype.FieldDeleteTime, field.TypeTime, value)
	}
	if etu.mutation.DeleteTimeCleared() {
		_spec.ClearField(entitytype.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := etu.mutation.EntityName(); ok {
		_spec.SetField(entitytype.FieldEntityName, field.TypeString, value)
	}
	if value, ok := etu.mutation.NotificationDescription(); ok {
		_spec.SetField(entitytype.FieldNotificationDescription, field.TypeString, value)
	}
	if etu.mutation.NotificationObjectIDsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entitytype.NotificationObjectIDsTable,
			Columns: []string{entitytype.NotificationObjectIDsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := etu.mutation.RemovedNotificationObjectIDsIDs(); len(nodes) > 0 && !etu.mutation.NotificationObjectIDsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entitytype.NotificationObjectIDsTable,
			Columns: []string{entitytype.NotificationObjectIDsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := etu.mutation.NotificationObjectIDsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entitytype.NotificationObjectIDsTable,
			Columns: []string{entitytype.NotificationObjectIDsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, etu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitytype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	etu.mutation.done = true
	return n, nil
}

// EntityTypeUpdateOne is the builder for updating a single EntityType entity.
type EntityTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntityTypeMutation
}

// SetDeleteTime sets the "delete_time" field.
func (etuo *EntityTypeUpdateOne) SetDeleteTime(t time.Time) *EntityTypeUpdateOne {
	etuo.mutation.SetDeleteTime(t)
	return etuo
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (etuo *EntityTypeUpdateOne) SetNillableDeleteTime(t *time.Time) *EntityTypeUpdateOne {
	if t != nil {
		etuo.SetDeleteTime(*t)
	}
	return etuo
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (etuo *EntityTypeUpdateOne) ClearDeleteTime() *EntityTypeUpdateOne {
	etuo.mutation.ClearDeleteTime()
	return etuo
}

// SetEntityName sets the "entityName" field.
func (etuo *EntityTypeUpdateOne) SetEntityName(s string) *EntityTypeUpdateOne {
	etuo.mutation.SetEntityName(s)
	return etuo
}

// SetNillableEntityName sets the "entityName" field if the given value is not nil.
func (etuo *EntityTypeUpdateOne) SetNillableEntityName(s *string) *EntityTypeUpdateOne {
	if s != nil {
		etuo.SetEntityName(*s)
	}
	return etuo
}

// SetNotificationDescription sets the "notificationDescription" field.
func (etuo *EntityTypeUpdateOne) SetNotificationDescription(s string) *EntityTypeUpdateOne {
	etuo.mutation.SetNotificationDescription(s)
	return etuo
}

// SetNillableNotificationDescription sets the "notificationDescription" field if the given value is not nil.
func (etuo *EntityTypeUpdateOne) SetNillableNotificationDescription(s *string) *EntityTypeUpdateOne {
	if s != nil {
		etuo.SetNotificationDescription(*s)
	}
	return etuo
}

// AddNotificationObjectIDIDs adds the "notificationObjectIDs" edge to the NotificationObjectID entity by IDs.
func (etuo *EntityTypeUpdateOne) AddNotificationObjectIDIDs(ids ...int) *EntityTypeUpdateOne {
	etuo.mutation.AddNotificationObjectIDIDs(ids...)
	return etuo
}

// AddNotificationObjectIDs adds the "notificationObjectIDs" edges to the NotificationObjectID entity.
func (etuo *EntityTypeUpdateOne) AddNotificationObjectIDs(n ...*NotificationObjectID) *EntityTypeUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return etuo.AddNotificationObjectIDIDs(ids...)
}

// Mutation returns the EntityTypeMutation object of the builder.
func (etuo *EntityTypeUpdateOne) Mutation() *EntityTypeMutation {
	return etuo.mutation
}

// ClearNotificationObjectIDs clears all "notificationObjectIDs" edges to the NotificationObjectID entity.
func (etuo *EntityTypeUpdateOne) ClearNotificationObjectIDs() *EntityTypeUpdateOne {
	etuo.mutation.ClearNotificationObjectIDs()
	return etuo
}

// RemoveNotificationObjectIDIDs removes the "notificationObjectIDs" edge to NotificationObjectID entities by IDs.
func (etuo *EntityTypeUpdateOne) RemoveNotificationObjectIDIDs(ids ...int) *EntityTypeUpdateOne {
	etuo.mutation.RemoveNotificationObjectIDIDs(ids...)
	return etuo
}

// RemoveNotificationObjectIDs removes "notificationObjectIDs" edges to NotificationObjectID entities.
func (etuo *EntityTypeUpdateOne) RemoveNotificationObjectIDs(n ...*NotificationObjectID) *EntityTypeUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return etuo.RemoveNotificationObjectIDIDs(ids...)
}

// Where appends a list predicates to the EntityTypeUpdate builder.
func (etuo *EntityTypeUpdateOne) Where(ps ...predicate.EntityType) *EntityTypeUpdateOne {
	etuo.mutation.Where(ps...)
	return etuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (etuo *EntityTypeUpdateOne) Select(field string, fields ...string) *EntityTypeUpdateOne {
	etuo.fields = append([]string{field}, fields...)
	return etuo
}

// Save executes the query and returns the updated EntityType entity.
func (etuo *EntityTypeUpdateOne) Save(ctx context.Context) (*EntityType, error) {
	return withHooks(ctx, etuo.sqlSave, etuo.mutation, etuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (etuo *EntityTypeUpdateOne) SaveX(ctx context.Context) *EntityType {
	node, err := etuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (etuo *EntityTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := etuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (etuo *EntityTypeUpdateOne) ExecX(ctx context.Context) {
	if err := etuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (etuo *EntityTypeUpdateOne) sqlSave(ctx context.Context) (_node *EntityType, err error) {
	_spec := sqlgraph.NewUpdateSpec(entitytype.Table, entitytype.Columns, sqlgraph.NewFieldSpec(entitytype.FieldID, field.TypeInt))
	id, ok := etuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntityType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := etuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitytype.FieldID)
		for _, f := range fields {
			if !entitytype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entitytype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := etuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := etuo.mutation.DeleteTime(); ok {
		_spec.SetField(entitytype.FieldDeleteTime, field.TypeTime, value)
	}
	if etuo.mutation.DeleteTimeCleared() {
		_spec.ClearField(entitytype.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := etuo.mutation.EntityName(); ok {
		_spec.SetField(entitytype.FieldEntityName, field.TypeString, value)
	}
	if value, ok := etuo.mutation.NotificationDescription(); ok {
		_spec.SetField(entitytype.FieldNotificationDescription, field.TypeString, value)
	}
	if etuo.mutation.NotificationObjectIDsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entitytype.NotificationObjectIDsTable,
			Columns: []string{entitytype.NotificationObjectIDsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := etuo.mutation.RemovedNotificationObjectIDsIDs(); len(nodes) > 0 && !etuo.mutation.NotificationObjectIDsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entitytype.NotificationObjectIDsTable,
			Columns: []string{entitytype.NotificationObjectIDsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := etuo.mutation.NotificationObjectIDsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entitytype.NotificationObjectIDsTable,
			Columns: []string{entitytype.NotificationObjectIDsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EntityType{config: etuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, etuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitytype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	etuo.mutation.done = true
	return _node, nil
}
