// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"notification-service/ent/friendship"
	"notification-service/ent/friendshipstatus"
	"notification-service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendshipStatusQuery is the builder for querying FriendshipStatus entities.
type FriendshipStatusQuery struct {
	config
	ctx             *QueryContext
	order           []friendshipstatus.OrderOption
	inters          []Interceptor
	predicates      []predicate.FriendshipStatus
	withFriendships *FriendshipQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FriendshipStatusQuery builder.
func (fsq *FriendshipStatusQuery) Where(ps ...predicate.FriendshipStatus) *FriendshipStatusQuery {
	fsq.predicates = append(fsq.predicates, ps...)
	return fsq
}

// Limit the number of records to be returned by this query.
func (fsq *FriendshipStatusQuery) Limit(limit int) *FriendshipStatusQuery {
	fsq.ctx.Limit = &limit
	return fsq
}

// Offset to start from.
func (fsq *FriendshipStatusQuery) Offset(offset int) *FriendshipStatusQuery {
	fsq.ctx.Offset = &offset
	return fsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fsq *FriendshipStatusQuery) Unique(unique bool) *FriendshipStatusQuery {
	fsq.ctx.Unique = &unique
	return fsq
}

// Order specifies how the records should be ordered.
func (fsq *FriendshipStatusQuery) Order(o ...friendshipstatus.OrderOption) *FriendshipStatusQuery {
	fsq.order = append(fsq.order, o...)
	return fsq
}

// QueryFriendships chains the current query on the "friendships" edge.
func (fsq *FriendshipStatusQuery) QueryFriendships() *FriendshipQuery {
	query := (&FriendshipClient{config: fsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(friendshipstatus.Table, friendshipstatus.FieldID, selector),
			sqlgraph.To(friendship.Table, friendship.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, friendshipstatus.FriendshipsTable, friendshipstatus.FriendshipsColumn),
		)
		fromU = sqlgraph.SetNeighbors(fsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FriendshipStatus entity from the query.
// Returns a *NotFoundError when no FriendshipStatus was found.
func (fsq *FriendshipStatusQuery) First(ctx context.Context) (*FriendshipStatus, error) {
	nodes, err := fsq.Limit(1).All(setContextOp(ctx, fsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{friendshipstatus.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fsq *FriendshipStatusQuery) FirstX(ctx context.Context) *FriendshipStatus {
	node, err := fsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FriendshipStatus ID from the query.
// Returns a *NotFoundError when no FriendshipStatus ID was found.
func (fsq *FriendshipStatusQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(1).IDs(setContextOp(ctx, fsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{friendshipstatus.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fsq *FriendshipStatusQuery) FirstIDX(ctx context.Context) int {
	id, err := fsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FriendshipStatus entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FriendshipStatus entity is found.
// Returns a *NotFoundError when no FriendshipStatus entities are found.
func (fsq *FriendshipStatusQuery) Only(ctx context.Context) (*FriendshipStatus, error) {
	nodes, err := fsq.Limit(2).All(setContextOp(ctx, fsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{friendshipstatus.Label}
	default:
		return nil, &NotSingularError{friendshipstatus.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fsq *FriendshipStatusQuery) OnlyX(ctx context.Context) *FriendshipStatus {
	node, err := fsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FriendshipStatus ID in the query.
// Returns a *NotSingularError when more than one FriendshipStatus ID is found.
// Returns a *NotFoundError when no entities are found.
func (fsq *FriendshipStatusQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(2).IDs(setContextOp(ctx, fsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{friendshipstatus.Label}
	default:
		err = &NotSingularError{friendshipstatus.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fsq *FriendshipStatusQuery) OnlyIDX(ctx context.Context) int {
	id, err := fsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FriendshipStatusSlice.
func (fsq *FriendshipStatusQuery) All(ctx context.Context) ([]*FriendshipStatus, error) {
	ctx = setContextOp(ctx, fsq.ctx, "All")
	if err := fsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FriendshipStatus, *FriendshipStatusQuery]()
	return withInterceptors[[]*FriendshipStatus](ctx, fsq, qr, fsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fsq *FriendshipStatusQuery) AllX(ctx context.Context) []*FriendshipStatus {
	nodes, err := fsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FriendshipStatus IDs.
func (fsq *FriendshipStatusQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fsq.ctx.Unique == nil && fsq.path != nil {
		fsq.Unique(true)
	}
	ctx = setContextOp(ctx, fsq.ctx, "IDs")
	if err = fsq.Select(friendshipstatus.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fsq *FriendshipStatusQuery) IDsX(ctx context.Context) []int {
	ids, err := fsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fsq *FriendshipStatusQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fsq.ctx, "Count")
	if err := fsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fsq, querierCount[*FriendshipStatusQuery](), fsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fsq *FriendshipStatusQuery) CountX(ctx context.Context) int {
	count, err := fsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fsq *FriendshipStatusQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fsq.ctx, "Exist")
	switch _, err := fsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fsq *FriendshipStatusQuery) ExistX(ctx context.Context) bool {
	exist, err := fsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FriendshipStatusQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fsq *FriendshipStatusQuery) Clone() *FriendshipStatusQuery {
	if fsq == nil {
		return nil
	}
	return &FriendshipStatusQuery{
		config:          fsq.config,
		ctx:             fsq.ctx.Clone(),
		order:           append([]friendshipstatus.OrderOption{}, fsq.order...),
		inters:          append([]Interceptor{}, fsq.inters...),
		predicates:      append([]predicate.FriendshipStatus{}, fsq.predicates...),
		withFriendships: fsq.withFriendships.Clone(),
		// clone intermediate query.
		sql:  fsq.sql.Clone(),
		path: fsq.path,
	}
}

// WithFriendships tells the query-builder to eager-load the nodes that are connected to
// the "friendships" edge. The optional arguments are used to configure the query builder of the edge.
func (fsq *FriendshipStatusQuery) WithFriendships(opts ...func(*FriendshipQuery)) *FriendshipStatusQuery {
	query := (&FriendshipClient{config: fsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fsq.withFriendships = query
	return fsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FriendshipStatus.Query().
//		GroupBy(friendshipstatus.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fsq *FriendshipStatusQuery) GroupBy(field string, fields ...string) *FriendshipStatusGroupBy {
	fsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FriendshipStatusGroupBy{build: fsq}
	grbuild.flds = &fsq.ctx.Fields
	grbuild.label = friendshipstatus.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.FriendshipStatus.Query().
//		Select(friendshipstatus.FieldCreatedAt).
//		Scan(ctx, &v)
func (fsq *FriendshipStatusQuery) Select(fields ...string) *FriendshipStatusSelect {
	fsq.ctx.Fields = append(fsq.ctx.Fields, fields...)
	sbuild := &FriendshipStatusSelect{FriendshipStatusQuery: fsq}
	sbuild.label = friendshipstatus.Label
	sbuild.flds, sbuild.scan = &fsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FriendshipStatusSelect configured with the given aggregations.
func (fsq *FriendshipStatusQuery) Aggregate(fns ...AggregateFunc) *FriendshipStatusSelect {
	return fsq.Select().Aggregate(fns...)
}

func (fsq *FriendshipStatusQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fsq); err != nil {
				return err
			}
		}
	}
	for _, f := range fsq.ctx.Fields {
		if !friendshipstatus.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fsq.path != nil {
		prev, err := fsq.path(ctx)
		if err != nil {
			return err
		}
		fsq.sql = prev
	}
	return nil
}

func (fsq *FriendshipStatusQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FriendshipStatus, error) {
	var (
		nodes       = []*FriendshipStatus{}
		_spec       = fsq.querySpec()
		loadedTypes = [1]bool{
			fsq.withFriendships != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FriendshipStatus).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FriendshipStatus{config: fsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fsq.withFriendships; query != nil {
		if err := fsq.loadFriendships(ctx, query, nodes,
			func(n *FriendshipStatus) { n.Edges.Friendships = []*Friendship{} },
			func(n *FriendshipStatus, e *Friendship) { n.Edges.Friendships = append(n.Edges.Friendships, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fsq *FriendshipStatusQuery) loadFriendships(ctx context.Context, query *FriendshipQuery, nodes []*FriendshipStatus, init func(*FriendshipStatus), assign func(*FriendshipStatus, *Friendship)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*FriendshipStatus)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Friendship(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(friendshipstatus.FriendshipsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.friendship_status_friendships
		if fk == nil {
			return fmt.Errorf(`foreign-key "friendship_status_friendships" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "friendship_status_friendships" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fsq *FriendshipStatusQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fsq.querySpec()
	_spec.Node.Columns = fsq.ctx.Fields
	if len(fsq.ctx.Fields) > 0 {
		_spec.Unique = fsq.ctx.Unique != nil && *fsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fsq.driver, _spec)
}

func (fsq *FriendshipStatusQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(friendshipstatus.Table, friendshipstatus.Columns, sqlgraph.NewFieldSpec(friendshipstatus.FieldID, field.TypeInt))
	_spec.From = fsq.sql
	if unique := fsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fsq.path != nil {
		_spec.Unique = true
	}
	if fields := fsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, friendshipstatus.FieldID)
		for i := range fields {
			if fields[i] != friendshipstatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fsq *FriendshipStatusQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fsq.driver.Dialect())
	t1 := builder.Table(friendshipstatus.Table)
	columns := fsq.ctx.Fields
	if len(columns) == 0 {
		columns = friendshipstatus.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fsq.sql != nil {
		selector = fsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fsq.ctx.Unique != nil && *fsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fsq.predicates {
		p(selector)
	}
	for _, p := range fsq.order {
		p(selector)
	}
	if offset := fsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FriendshipStatusGroupBy is the group-by builder for FriendshipStatus entities.
type FriendshipStatusGroupBy struct {
	selector
	build *FriendshipStatusQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fsgb *FriendshipStatusGroupBy) Aggregate(fns ...AggregateFunc) *FriendshipStatusGroupBy {
	fsgb.fns = append(fsgb.fns, fns...)
	return fsgb
}

// Scan applies the selector query and scans the result into the given value.
func (fsgb *FriendshipStatusGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fsgb.build.ctx, "GroupBy")
	if err := fsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FriendshipStatusQuery, *FriendshipStatusGroupBy](ctx, fsgb.build, fsgb, fsgb.build.inters, v)
}

func (fsgb *FriendshipStatusGroupBy) sqlScan(ctx context.Context, root *FriendshipStatusQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fsgb.fns))
	for _, fn := range fsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fsgb.flds)+len(fsgb.fns))
		for _, f := range *fsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FriendshipStatusSelect is the builder for selecting fields of FriendshipStatus entities.
type FriendshipStatusSelect struct {
	*FriendshipStatusQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fss *FriendshipStatusSelect) Aggregate(fns ...AggregateFunc) *FriendshipStatusSelect {
	fss.fns = append(fss.fns, fns...)
	return fss
}

// Scan applies the selector query and scans the result into the given value.
func (fss *FriendshipStatusSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fss.ctx, "Select")
	if err := fss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FriendshipStatusQuery, *FriendshipStatusSelect](ctx, fss.FriendshipStatusQuery, fss, fss.inters, v)
}

func (fss *FriendshipStatusSelect) sqlScan(ctx context.Context, root *FriendshipStatusQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fss.fns))
	for _, fn := range fss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
