// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"notification-service/ent/friendshipstatus"
	"notification-service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendshipStatusDelete is the builder for deleting a FriendshipStatus entity.
type FriendshipStatusDelete struct {
	config
	hooks    []Hook
	mutation *FriendshipStatusMutation
}

// Where appends a list predicates to the FriendshipStatusDelete builder.
func (fsd *FriendshipStatusDelete) Where(ps ...predicate.FriendshipStatus) *FriendshipStatusDelete {
	fsd.mutation.Where(ps...)
	return fsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fsd *FriendshipStatusDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fsd.sqlExec, fsd.mutation, fsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fsd *FriendshipStatusDelete) ExecX(ctx context.Context) int {
	n, err := fsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fsd *FriendshipStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(friendshipstatus.Table, sqlgraph.NewFieldSpec(friendshipstatus.FieldID, field.TypeInt))
	if ps := fsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fsd.mutation.done = true
	return affected, err
}

// FriendshipStatusDeleteOne is the builder for deleting a single FriendshipStatus entity.
type FriendshipStatusDeleteOne struct {
	fsd *FriendshipStatusDelete
}

// Where appends a list predicates to the FriendshipStatusDelete builder.
func (fsdo *FriendshipStatusDeleteOne) Where(ps ...predicate.FriendshipStatus) *FriendshipStatusDeleteOne {
	fsdo.fsd.mutation.Where(ps...)
	return fsdo
}

// Exec executes the deletion query.
func (fsdo *FriendshipStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := fsdo.fsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{friendshipstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fsdo *FriendshipStatusDeleteOne) ExecX(ctx context.Context) {
	if err := fsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
