// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"notification-service/ent/notificationchange"
	"notification-service/ent/notificationobjectid"
	"notification-service/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationChangeCreate is the builder for creating a NotificationChange entity.
type NotificationChangeCreate struct {
	config
	mutation *NotificationChangeMutation
	hooks    []Hook
}

// SetDeleteTime sets the "delete_time" field.
func (ncc *NotificationChangeCreate) SetDeleteTime(t time.Time) *NotificationChangeCreate {
	ncc.mutation.SetDeleteTime(t)
	return ncc
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (ncc *NotificationChangeCreate) SetNillableDeleteTime(t *time.Time) *NotificationChangeCreate {
	if t != nil {
		ncc.SetDeleteTime(*t)
	}
	return ncc
}

// SetUserIDID sets the "userID" edge to the User entity by ID.
func (ncc *NotificationChangeCreate) SetUserIDID(id int) *NotificationChangeCreate {
	ncc.mutation.SetUserIDID(id)
	return ncc
}

// SetNillableUserIDID sets the "userID" edge to the User entity by ID if the given value is not nil.
func (ncc *NotificationChangeCreate) SetNillableUserIDID(id *int) *NotificationChangeCreate {
	if id != nil {
		ncc = ncc.SetUserIDID(*id)
	}
	return ncc
}

// SetUserID sets the "userID" edge to the User entity.
func (ncc *NotificationChangeCreate) SetUserID(u *User) *NotificationChangeCreate {
	return ncc.SetUserIDID(u.ID)
}

// SetNotificationObjectIDID sets the "notificationObjectID" edge to the NotificationObjectID entity by ID.
func (ncc *NotificationChangeCreate) SetNotificationObjectIDID(id int) *NotificationChangeCreate {
	ncc.mutation.SetNotificationObjectIDID(id)
	return ncc
}

// SetNillableNotificationObjectIDID sets the "notificationObjectID" edge to the NotificationObjectID entity by ID if the given value is not nil.
func (ncc *NotificationChangeCreate) SetNillableNotificationObjectIDID(id *int) *NotificationChangeCreate {
	if id != nil {
		ncc = ncc.SetNotificationObjectIDID(*id)
	}
	return ncc
}

// SetNotificationObjectID sets the "notificationObjectID" edge to the NotificationObjectID entity.
func (ncc *NotificationChangeCreate) SetNotificationObjectID(n *NotificationObjectID) *NotificationChangeCreate {
	return ncc.SetNotificationObjectIDID(n.ID)
}

// Mutation returns the NotificationChangeMutation object of the builder.
func (ncc *NotificationChangeCreate) Mutation() *NotificationChangeMutation {
	return ncc.mutation
}

// Save creates the NotificationChange in the database.
func (ncc *NotificationChangeCreate) Save(ctx context.Context) (*NotificationChange, error) {
	return withHooks(ctx, ncc.sqlSave, ncc.mutation, ncc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ncc *NotificationChangeCreate) SaveX(ctx context.Context) *NotificationChange {
	v, err := ncc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncc *NotificationChangeCreate) Exec(ctx context.Context) error {
	_, err := ncc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncc *NotificationChangeCreate) ExecX(ctx context.Context) {
	if err := ncc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ncc *NotificationChangeCreate) check() error {
	return nil
}

func (ncc *NotificationChangeCreate) sqlSave(ctx context.Context) (*NotificationChange, error) {
	if err := ncc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ncc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ncc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ncc.mutation.id = &_node.ID
	ncc.mutation.done = true
	return _node, nil
}

func (ncc *NotificationChangeCreate) createSpec() (*NotificationChange, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationChange{config: ncc.config}
		_spec = sqlgraph.NewCreateSpec(notificationchange.Table, sqlgraph.NewFieldSpec(notificationchange.FieldID, field.TypeInt))
	)
	if value, ok := ncc.mutation.DeleteTime(); ok {
		_spec.SetField(notificationchange.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = value
	}
	if nodes := ncc.mutation.UserIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationchange.UserIDTable,
			Columns: []string{notificationchange.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_notification_changes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ncc.mutation.NotificationObjectIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationchange.NotificationObjectIDTable,
			Columns: []string{notificationchange.NotificationObjectIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.notification_object_id_notification_changes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationChangeCreateBulk is the builder for creating many NotificationChange entities in bulk.
type NotificationChangeCreateBulk struct {
	config
	err      error
	builders []*NotificationChangeCreate
}

// Save creates the NotificationChange entities in the database.
func (nccb *NotificationChangeCreateBulk) Save(ctx context.Context) ([]*NotificationChange, error) {
	if nccb.err != nil {
		return nil, nccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(nccb.builders))
	nodes := make([]*NotificationChange, len(nccb.builders))
	mutators := make([]Mutator, len(nccb.builders))
	for i := range nccb.builders {
		func(i int, root context.Context) {
			builder := nccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationChangeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nccb *NotificationChangeCreateBulk) SaveX(ctx context.Context) []*NotificationChange {
	v, err := nccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nccb *NotificationChangeCreateBulk) Exec(ctx context.Context) error {
	_, err := nccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nccb *NotificationChangeCreateBulk) ExecX(ctx context.Context) {
	if err := nccb.Exec(ctx); err != nil {
		panic(err)
	}
}
