// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notification-service/ent/notification"
	"notification-service/ent/notificationobjectid"
	"notification-service/ent/predicate"
	"notification-service/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (nu *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetDeleteTime sets the "delete_time" field.
func (nu *NotificationUpdate) SetDeleteTime(t time.Time) *NotificationUpdate {
	nu.mutation.SetDeleteTime(t)
	return nu
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableDeleteTime(t *time.Time) *NotificationUpdate {
	if t != nil {
		nu.SetDeleteTime(*t)
	}
	return nu
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (nu *NotificationUpdate) ClearDeleteTime() *NotificationUpdate {
	nu.mutation.ClearDeleteTime()
	return nu
}

// SetIsRead sets the "isRead" field.
func (nu *NotificationUpdate) SetIsRead(b bool) *NotificationUpdate {
	nu.mutation.SetIsRead(b)
	return nu
}

// SetNillableIsRead sets the "isRead" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableIsRead(b *bool) *NotificationUpdate {
	if b != nil {
		nu.SetIsRead(*b)
	}
	return nu
}

// SetNotificationObjectIDID sets the "notificationObjectID" edge to the NotificationObjectID entity by ID.
func (nu *NotificationUpdate) SetNotificationObjectIDID(id int) *NotificationUpdate {
	nu.mutation.SetNotificationObjectIDID(id)
	return nu
}

// SetNillableNotificationObjectIDID sets the "notificationObjectID" edge to the NotificationObjectID entity by ID if the given value is not nil.
func (nu *NotificationUpdate) SetNillableNotificationObjectIDID(id *int) *NotificationUpdate {
	if id != nil {
		nu = nu.SetNotificationObjectIDID(*id)
	}
	return nu
}

// SetNotificationObjectID sets the "notificationObjectID" edge to the NotificationObjectID entity.
func (nu *NotificationUpdate) SetNotificationObjectID(n *NotificationObjectID) *NotificationUpdate {
	return nu.SetNotificationObjectIDID(n.ID)
}

// SetUserIDID sets the "userID" edge to the User entity by ID.
func (nu *NotificationUpdate) SetUserIDID(id int) *NotificationUpdate {
	nu.mutation.SetUserIDID(id)
	return nu
}

// SetNillableUserIDID sets the "userID" edge to the User entity by ID if the given value is not nil.
func (nu *NotificationUpdate) SetNillableUserIDID(id *int) *NotificationUpdate {
	if id != nil {
		nu = nu.SetUserIDID(*id)
	}
	return nu
}

// SetUserID sets the "userID" edge to the User entity.
func (nu *NotificationUpdate) SetUserID(u *User) *NotificationUpdate {
	return nu.SetUserIDID(u.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (nu *NotificationUpdate) Mutation() *NotificationMutation {
	return nu.mutation
}

// ClearNotificationObjectID clears the "notificationObjectID" edge to the NotificationObjectID entity.
func (nu *NotificationUpdate) ClearNotificationObjectID() *NotificationUpdate {
	nu.mutation.ClearNotificationObjectID()
	return nu
}

// ClearUserID clears the "userID" edge to the User entity.
func (nu *NotificationUpdate) ClearUserID() *NotificationUpdate {
	nu.mutation.ClearUserID()
	return nu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NotificationUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (nu *NotificationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.DeleteTime(); ok {
		_spec.SetField(notification.FieldDeleteTime, field.TypeTime, value)
	}
	if nu.mutation.DeleteTimeCleared() {
		_spec.ClearField(notification.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := nu.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if nu.mutation.NotificationObjectIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.NotificationObjectIDTable,
			Columns: []string{notification.NotificationObjectIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.NotificationObjectIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.NotificationObjectIDTable,
			Columns: []string{notification.NotificationObjectIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nu.mutation.UserIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.UserIDTable,
			Columns: []string{notification.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.UserIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.UserIDTable,
			Columns: []string{notification.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetDeleteTime sets the "delete_time" field.
func (nuo *NotificationUpdateOne) SetDeleteTime(t time.Time) *NotificationUpdateOne {
	nuo.mutation.SetDeleteTime(t)
	return nuo
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableDeleteTime(t *time.Time) *NotificationUpdateOne {
	if t != nil {
		nuo.SetDeleteTime(*t)
	}
	return nuo
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (nuo *NotificationUpdateOne) ClearDeleteTime() *NotificationUpdateOne {
	nuo.mutation.ClearDeleteTime()
	return nuo
}

// SetIsRead sets the "isRead" field.
func (nuo *NotificationUpdateOne) SetIsRead(b bool) *NotificationUpdateOne {
	nuo.mutation.SetIsRead(b)
	return nuo
}

// SetNillableIsRead sets the "isRead" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableIsRead(b *bool) *NotificationUpdateOne {
	if b != nil {
		nuo.SetIsRead(*b)
	}
	return nuo
}

// SetNotificationObjectIDID sets the "notificationObjectID" edge to the NotificationObjectID entity by ID.
func (nuo *NotificationUpdateOne) SetNotificationObjectIDID(id int) *NotificationUpdateOne {
	nuo.mutation.SetNotificationObjectIDID(id)
	return nuo
}

// SetNillableNotificationObjectIDID sets the "notificationObjectID" edge to the NotificationObjectID entity by ID if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableNotificationObjectIDID(id *int) *NotificationUpdateOne {
	if id != nil {
		nuo = nuo.SetNotificationObjectIDID(*id)
	}
	return nuo
}

// SetNotificationObjectID sets the "notificationObjectID" edge to the NotificationObjectID entity.
func (nuo *NotificationUpdateOne) SetNotificationObjectID(n *NotificationObjectID) *NotificationUpdateOne {
	return nuo.SetNotificationObjectIDID(n.ID)
}

// SetUserIDID sets the "userID" edge to the User entity by ID.
func (nuo *NotificationUpdateOne) SetUserIDID(id int) *NotificationUpdateOne {
	nuo.mutation.SetUserIDID(id)
	return nuo
}

// SetNillableUserIDID sets the "userID" edge to the User entity by ID if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableUserIDID(id *int) *NotificationUpdateOne {
	if id != nil {
		nuo = nuo.SetUserIDID(*id)
	}
	return nuo
}

// SetUserID sets the "userID" edge to the User entity.
func (nuo *NotificationUpdateOne) SetUserID(u *User) *NotificationUpdateOne {
	return nuo.SetUserIDID(u.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (nuo *NotificationUpdateOne) Mutation() *NotificationMutation {
	return nuo.mutation
}

// ClearNotificationObjectID clears the "notificationObjectID" edge to the NotificationObjectID entity.
func (nuo *NotificationUpdateOne) ClearNotificationObjectID() *NotificationUpdateOne {
	nuo.mutation.ClearNotificationObjectID()
	return nuo
}

// ClearUserID clears the "userID" edge to the User entity.
func (nuo *NotificationUpdateOne) ClearUserID() *NotificationUpdateOne {
	nuo.mutation.ClearUserID()
	return nuo
}

// Where appends a list predicates to the NotificationUpdate builder.
func (nuo *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Notification entity.
func (nuo *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (nuo *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.DeleteTime(); ok {
		_spec.SetField(notification.FieldDeleteTime, field.TypeTime, value)
	}
	if nuo.mutation.DeleteTimeCleared() {
		_spec.ClearField(notification.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := nuo.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if nuo.mutation.NotificationObjectIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.NotificationObjectIDTable,
			Columns: []string{notification.NotificationObjectIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.NotificationObjectIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.NotificationObjectIDTable,
			Columns: []string{notification.NotificationObjectIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationobjectid.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nuo.mutation.UserIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.UserIDTable,
			Columns: []string{notification.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.UserIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.UserIDTable,
			Columns: []string{notification.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Notification{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
