// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"notification-service/ent/notification"
	"notification-service/ent/notificationobjectid"
	"notification-service/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Notification is the model entity for the Notification schema.
type Notification struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DeleteTime holds the value of the "delete_time" field.
	DeleteTime time.Time `json:"delete_time,omitempty"`
	// IsRead holds the value of the "isRead" field.
	IsRead bool `json:"isRead,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationQuery when eager-loading is set.
	Edges                                NotificationEdges `json:"edges"`
	notification_object_id_notifications *int
	user_notifications                   *int
	selectValues                         sql.SelectValues
}

// NotificationEdges holds the relations/edges for other nodes in the graph.
type NotificationEdges struct {
	// NotificationObjectID holds the value of the notificationObjectID edge.
	NotificationObjectID *NotificationObjectID `json:"notificationObjectID,omitempty"`
	// UserID holds the value of the userID edge.
	UserID *User `json:"userID,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// NotificationObjectIDOrErr returns the NotificationObjectID value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationEdges) NotificationObjectIDOrErr() (*NotificationObjectID, error) {
	if e.NotificationObjectID != nil {
		return e.NotificationObjectID, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: notificationobjectid.Label}
	}
	return nil, &NotLoadedError{edge: "notificationObjectID"}
}

// UserIDOrErr returns the UserID value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationEdges) UserIDOrErr() (*User, error) {
	if e.UserID != nil {
		return e.UserID, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "userID"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Notification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notification.FieldIsRead:
			values[i] = new(sql.NullBool)
		case notification.FieldID:
			values[i] = new(sql.NullInt64)
		case notification.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		case notification.ForeignKeys[0]: // notification_object_id_notifications
			values[i] = new(sql.NullInt64)
		case notification.ForeignKeys[1]: // user_notifications
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Notification fields.
func (n *Notification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			n.ID = int(value.Int64)
		case notification.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				n.DeleteTime = value.Time
			}
		case notification.FieldIsRead:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isRead", values[i])
			} else if value.Valid {
				n.IsRead = value.Bool
			}
		case notification.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field notification_object_id_notifications", value)
			} else if value.Valid {
				n.notification_object_id_notifications = new(int)
				*n.notification_object_id_notifications = int(value.Int64)
			}
		case notification.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_notifications", value)
			} else if value.Valid {
				n.user_notifications = new(int)
				*n.user_notifications = int(value.Int64)
			}
		default:
			n.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Notification.
// This includes values selected through modifiers, order, etc.
func (n *Notification) Value(name string) (ent.Value, error) {
	return n.selectValues.Get(name)
}

// QueryNotificationObjectID queries the "notificationObjectID" edge of the Notification entity.
func (n *Notification) QueryNotificationObjectID() *NotificationObjectIDQuery {
	return NewNotificationClient(n.config).QueryNotificationObjectID(n)
}

// QueryUserID queries the "userID" edge of the Notification entity.
func (n *Notification) QueryUserID() *UserQuery {
	return NewNotificationClient(n.config).QueryUserID(n)
}

// Update returns a builder for updating this Notification.
// Note that you need to call Notification.Unwrap() before calling this method if this Notification
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *Notification) Update() *NotificationUpdateOne {
	return NewNotificationClient(n.config).UpdateOne(n)
}

// Unwrap unwraps the Notification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *Notification) Unwrap() *Notification {
	_tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: Notification is not a transactional entity")
	}
	n.config.driver = _tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *Notification) String() string {
	var builder strings.Builder
	builder.WriteString("Notification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", n.ID))
	builder.WriteString("delete_time=")
	builder.WriteString(n.DeleteTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("isRead=")
	builder.WriteString(fmt.Sprintf("%v", n.IsRead))
	builder.WriteByte(')')
	return builder.String()
}

// Notifications is a parsable slice of Notification.
type Notifications []*Notification
