// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"notification-service/ent/toktok"
	"notification-service/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TokTok is the model entity for the TokTok schema.
type TokTok struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DeleteTime holds the value of the "delete_time" field.
	DeleteTime time.Time `json:"delete_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TokTokQuery when eager-loading is set.
	Edges                 TokTokEdges `json:"edges"`
	user_toktoks_receiver *int
	user_toktoks_sender   *int
	selectValues          sql.SelectValues
}

// TokTokEdges holds the relations/edges for other nodes in the graph.
type TokTokEdges struct {
	// ReceiverID holds the value of the receiverID edge.
	ReceiverID *User `json:"receiverID,omitempty"`
	// SenderID holds the value of the senderID edge.
	SenderID *User `json:"senderID,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ReceiverIDOrErr returns the ReceiverID value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TokTokEdges) ReceiverIDOrErr() (*User, error) {
	if e.ReceiverID != nil {
		return e.ReceiverID, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "receiverID"}
}

// SenderIDOrErr returns the SenderID value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TokTokEdges) SenderIDOrErr() (*User, error) {
	if e.SenderID != nil {
		return e.SenderID, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "senderID"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TokTok) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case toktok.FieldID:
			values[i] = new(sql.NullInt64)
		case toktok.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		case toktok.ForeignKeys[0]: // user_toktoks_receiver
			values[i] = new(sql.NullInt64)
		case toktok.ForeignKeys[1]: // user_toktoks_sender
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TokTok fields.
func (tt *TokTok) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case toktok.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tt.ID = int(value.Int64)
		case toktok.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				tt.DeleteTime = value.Time
			}
		case toktok.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_toktoks_receiver", value)
			} else if value.Valid {
				tt.user_toktoks_receiver = new(int)
				*tt.user_toktoks_receiver = int(value.Int64)
			}
		case toktok.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_toktoks_sender", value)
			} else if value.Valid {
				tt.user_toktoks_sender = new(int)
				*tt.user_toktoks_sender = int(value.Int64)
			}
		default:
			tt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TokTok.
// This includes values selected through modifiers, order, etc.
func (tt *TokTok) Value(name string) (ent.Value, error) {
	return tt.selectValues.Get(name)
}

// QueryReceiverID queries the "receiverID" edge of the TokTok entity.
func (tt *TokTok) QueryReceiverID() *UserQuery {
	return NewTokTokClient(tt.config).QueryReceiverID(tt)
}

// QuerySenderID queries the "senderID" edge of the TokTok entity.
func (tt *TokTok) QuerySenderID() *UserQuery {
	return NewTokTokClient(tt.config).QuerySenderID(tt)
}

// Update returns a builder for updating this TokTok.
// Note that you need to call TokTok.Unwrap() before calling this method if this TokTok
// was returned from a transaction, and the transaction was committed or rolled back.
func (tt *TokTok) Update() *TokTokUpdateOne {
	return NewTokTokClient(tt.config).UpdateOne(tt)
}

// Unwrap unwraps the TokTok entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tt *TokTok) Unwrap() *TokTok {
	_tx, ok := tt.config.driver.(*txDriver)
	if !ok {
		panic("ent: TokTok is not a transactional entity")
	}
	tt.config.driver = _tx.drv
	return tt
}

// String implements the fmt.Stringer.
func (tt *TokTok) String() string {
	var builder strings.Builder
	builder.WriteString("TokTok(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tt.ID))
	builder.WriteString("delete_time=")
	builder.WriteString(tt.DeleteTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TokToks is a parsable slice of TokTok.
type TokToks []*TokTok
