// Code generated by ent, DO NOT EDIT.

package notificationchange

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the notificationchange type in the database.
	Label = "notification_change"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeActor holds the string denoting the actor edge name in mutations.
	EdgeActor = "actor"
	// EdgeNotificationObject holds the string denoting the notificationobject edge name in mutations.
	EdgeNotificationObject = "notificationObject"
	// Table holds the table name of the notificationchange in the database.
	Table = "notification_changes"
	// ActorTable is the table that holds the actor relation/edge.
	ActorTable = "notification_changes"
	// ActorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ActorInverseTable = "users"
	// ActorColumn is the table column denoting the actor relation/edge.
	ActorColumn = "user_notification_changes"
	// NotificationObjectTable is the table that holds the notificationObject relation/edge.
	NotificationObjectTable = "notification_changes"
	// NotificationObjectInverseTable is the table name for the NotificationObject entity.
	// It exists in this package in order to avoid circular dependency with the "notificationobject" package.
	NotificationObjectInverseTable = "notification_objects"
	// NotificationObjectColumn is the table column denoting the notificationObject relation/edge.
	NotificationObjectColumn = "notification_object_notification_changes"
)

// Columns holds all SQL columns for notificationchange fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "notification_changes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"notification_object_notification_changes",
	"user_notification_changes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "notification-service/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the NotificationChange queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByActorField orders the results by actor field.
func ByActorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActorStep(), sql.OrderByField(field, opts...))
	}
}

// ByNotificationObjectField orders the results by notificationObject field.
func ByNotificationObjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationObjectStep(), sql.OrderByField(field, opts...))
	}
}
func newActorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ActorTable, ActorColumn),
	)
}
func newNotificationObjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationObjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NotificationObjectTable, NotificationObjectColumn),
	)
}
