// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EntityType is the predicate function for entitytype builders.
type EntityType func(*sql.Selector)

// Friendship is the predicate function for friendship builders.
type Friendship func(*sql.Selector)

// FriendshipStatus is the predicate function for friendshipstatus builders.
type FriendshipStatus func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// NotificationChange is the predicate function for notificationchange builders.
type NotificationChange func(*sql.Selector)

// NotificationObject is the predicate function for notificationobject builders.
type NotificationObject func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
